# Data Mining Project: Epileptic Seizures

## Pre-processing

### Import packages

In [26]:
import numpy as np
import pandas as pd
from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree,metrics
from sklearn.metrics import roc_auc_score

### Read Data

In [12]:
data = pd.read_csv('data.csv',
                           sep= ',')

print ("Dataset Lenght:: ", len(data))
print ("Dataset Shape:: ", data.shape)

print ("Dataset:: ",
data.head())

Dataset Lenght::  11500
Dataset Shape::  (11500, 180)
Dataset::     Unnamed: 0   X1   X2   X3   X4   X5   X6   X7   X8   X9 ...  X170  X171  \
0  X21.V1.791  135  190  229  223  192  125   55   -9  -33 ...   -17   -15   
1  X15.V1.924  386  382  356  331  320  315  307  272  244 ...   164   150   
2     X8.V1.1  -32  -39  -47  -37  -32  -36  -57  -73  -85 ...    57    64   
3   X16.V1.60 -105 -101  -96  -92  -89  -95 -102 -100  -87 ...   -82   -81   
4   X20.V1.54   -9  -65  -98 -102  -78  -48  -16    0  -21 ...     4     2   

   X172  X173  X174  X175  X176  X177  X178  y  
0   -31   -77  -103  -127  -116   -83   -51  4  
1   146   152   157   156   154   143   129  1  
2    48    19   -12   -30   -35   -35   -36  5  
3   -80   -77   -85   -77   -72   -69   -65  5  
4   -12   -32   -41   -65   -83   -89   -73  5  

[5 rows x 180 columns]


#### Separating features from class

In [13]:
X = data.values[:, 1:178]
Y = data.values[:,179]

#### Creating training, validation and test set

In [29]:
X_train, X_test, y_train, y_test = train_test_split( X, Y, test_size = 0.34, random_state = 100)
X_train, X_val, y_train, y_val = train_test_split( X_train, y_train, test_size = 0.34, random_state = 100)

### Metrics

#### Confusion Matrix

In [36]:
def confusion_matrix(y_test, y_pred):
    print(metrics.confusion_matrix(y_test.astype(int), y_pred))

In [35]:
def accuracy(y_test, y_pred):
    print(metrics.accuracy_score(y_test.astype(int),y_pred)*100)    

In [37]:
def classificationreport(y_test, y_pred):
    print (metrics.classification_report(y_test.astype(int), y_pred))

In [38]:
def allmetrics(y_test,y_pred):
    confusion_matrix(y_test,y_pred)
    accuracy(y_test,y_pred)
    classificationreport(y_test,y_pred)

### Decision Tree

#### GINI Criterion

In [51]:
clf_gini = DecisionTreeClassifier(criterion="gini", splitter="best", 
max_depth=None, min_samples_split=2, min_samples_leaf=1, 
min_weight_fraction_leaf=0.0, max_features=None, random_state=None, 
max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, 
class_weight=None, presort=False
)


clf_gini.fit(X_train.astype(int), y_train.astype(int))

y_pred = clf_gini.predict(X_val)

##### Metrics result

In [52]:
allmetrics(y_val,y_pred)

[[357  50  55  45  15]
 [ 36 188 147  49  81]
 [ 15 161 178  68  90]
 [ 26  91  69 208 118]
 [  5 113 114  97 205]]
44.0139480821
             precision    recall  f1-score   support

          1       0.81      0.68      0.74       522
          2       0.31      0.38      0.34       501
          3       0.32      0.35      0.33       512
          4       0.45      0.41      0.42       512
          5       0.40      0.38      0.39       534

avg / total       0.46      0.44      0.45      2581



#### GINI Criterion Tuning

In [56]:
clf_gini = DecisionTreeClassifier(criterion="gini", splitter="best", 
max_depth=None, min_samples_split=2, min_samples_leaf=1, 
min_weight_fraction_leaf=0.0, max_features=None, random_state=None, 
max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, 
class_weight=None, presort=False
)


clf_gini.fit(X_train.astype(int), y_train.astype(int))

y_pred = clf_gini.predict(X_val)

ValueError: Unknown label type: 'unknown'